export const devConfig = {
    authenticationBackendUrl:'http://localhost:8084/FYP-backend/API/authentication/login',
    registrationBackendUrl:'http://localhost:8084/FYP-backend/API/registration',
    productCatalogueBackendUrl:'http://localhost:8084/FYP-backend/API/ProductCatalogue',
    productListBackendUrl:'http://localhost:8084/FYP-backend/API/ProductCatalogue/BeddingPatterns',
    profileBackendUrl:'http://localhost:8084/FYP-backend/API/profile',
    quickViewBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/GetBedding',
    fabricBackendUrl: 'http://localhost:8084/FYP-backend/API/FabricCatalogue/fabrics',
    filteredProductListBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    searchedProductListBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/search',
    getCartItemBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart/items',
    updateCartItemBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart/updateCartItems',
    updateCartBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart/updateCart',
    clearCartBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart/delete',
    getCartTotalPriceBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart/price',
    cartBackendUrl: 'http://localhost:8084/FYP-backend/API/Cart',
    paymentBackendUrl: 'http://localhost:8084/FYP-backend/API/Payment',
    addressBackendUrl: 'http://localhost:8084/FYP-backend/API/AddressService',
    orderBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderService',
    filterBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/GetFilters'
}