export const prodConfig = {
    authenticationBackendUrl:'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/authentication/login',
    registrationBackendUrl:'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/registration',
    productCatalogueBackendUrl:'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue',
    productListBackendUrl:'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/BeddingPatterns',
    profileBackendUrl:'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/profile',
    quickViewBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/GetBedding',
    fabricBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/FabricCatalogue/fabrics',
    productDetailsBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/customization',
    filteredProductListBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    searchedProductListBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/search',
    getCartItemBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart/items',
    updateCartItemBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart/updateCartItems',
    updateCartBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart/updateCart',
    clearCartBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart/delete',
    getCartTotalPriceBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart/price',
    cartBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Cart',
    paymentBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/Payment',
    addressBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/AddressService',
    filterBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/ProductCatalogue/GetFilters',
    orderBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/OrderService',
    promoBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/PromoService',
    mahoutBackendUrl: 'https://dmchpv8en06ax.cloudfront.net/FYP-backend/API/MahoutService'
}

