export const stagConfig = {
    authenticationBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/authentication/login',
    registrationBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/registration',
    productCatalogueBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue',
    productListBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/uniquePatterns',
    profileBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/profile',
    quickViewBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/product',
    fabricBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/FabricCatalogue/fabrics',
    productDetailsBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/customization',
    filteredProductListBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/filtersort',
    searchedProductListBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/search',
    getCartItemBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart/items',
    updateCartItemBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart/updateCartItems',
    updateCartBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart/updateCart',
    clearCartBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart/delete',
    getCartTotalPriceBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart/price',
    cartBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Cart',
    paymentBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/Payment',
    addressBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/AddressService',  
    filterBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/GetFilters',
    orderBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/OrderService',
    promoBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/PromoService',
    mahoutBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/MahoutService'
}