export const prodConfig = {
    authenticationBackendUrl:'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/authentication/admin/login',
    registrationBackendUrl:'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/registration/insert',
    productCatalogueBackendUrl:'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/ProductCatalogue',
    patternCatalogueBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/PatternCatalogue',
    fabricCatalogueBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/FabricCatalogue',
    staffBackendUrl:'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/staff',
    quickViewBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/ProductCatalogue/pattern',
    eCommerceWebsiteUrl: 'http://highlanderdeluxe.com',
    promoCodeBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/PromoService',
    orderBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/OrderService',
    orderStatusLogBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/OrderStatusLogService',
    orderItemBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/OrderItemService',
    filterBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/ProductCatalogue/GetFilters',
    filteredProductListBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    collectionBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/CollectionService',
    fabricBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/FabricService',
    colourBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/ColourService',
    patternBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/PatternService',
    beddingSizeBackendUrl: 'https://d10yqh2on3h6us.cloudfront.net/FYP-backend/API/BeddingSizeService'
}