export const prodConfig = {
    authenticationBackendUrl:'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/authentication/admin/login',
    registrationBackendUrl:'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/registration/insert',
    productCatalogueBackendUrl:'http://localhost:8084/FYP-backend/API/ProductCatalogue/BeddingPatterns',
    patternCatalogueBackendUrl: 'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/PatternCatalogue',
    fabricCatalogueBackendUrl: 'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/FabricCatalogue',
    staffBackendUrl:'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/staff',
    quickViewBackendUrl: 'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/pattern',
    eCommerceWebsiteUrl: 'http://highlander-app.s3-website-us-west-2.amazonaws.com',
    promoCodeBackendUrl: 'http://ec2-52-35-18-15.us-west-2.compute.amazonaws.com/FYP-backend/API/promoCode',
    orderBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderService',
    orderStatusLogBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderStatusLogService',
    orderItemBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderItemService',
    filterBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/GetFilters',
    filteredProductListBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    collectionBackendUrl: 'http://localhost:8084/FYP-backend/API/CollectionService',
    fabricBackendUrl: 'http://localhost:8084/FYP-backend/API/FabricService',
    colourBackendUrl: 'http://localhost:8084/FYP-backend/API/ColourService',
    patternBackendUrl: 'http://localhost:8084/FYP-backend/API/PatternService'    
}