export const stagConfig = {
    authenticationBackendUrl:'',
    registrationBackendUrl:'',
    productCatalogueBackendUrl:'http://localhost:8084/FYP-backend/API/ProductCatalogue/BeddingPatterns',
    patternCatalogueBackendUrl:'',
    fabricCatalogueBackendUrl:'',
    staffBackendUrl:'',
    quickViewBackendUrl:'',
    eCommerceWebsiteUrl: '',
    promoCodeBackendUrl: '',
    orderBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderService',
    orderStatusLogBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderStatusLogService',
    orderItemBackendUrl: 'http://localhost:8084/FYP-backend/API/OrderItemService',
    filterBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/GetFilters',
    filteredProductListBackendUrl: 'http://localhost:8084/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    collectionBackendUrl: 'http://localhost:8084/FYP-backend/API/CollectionService',
    fabricBackendUrl: 'http://localhost:8084/FYP-backend/API/FabricService',
    colourBackendUrl: 'http://localhost:8084/FYP-backend/API/ColourService',
    patternBackendUrl: 'http://localhost:8084/FYP-backend/API/PatternService'    
}