export const stagConfig = {
    authenticationBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/authentication/admin/login',
    registrationBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/registration/insert',
    productCatalogueBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue',
    patternCatalogueBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/PatternCatalogue',
    fabricCatalogueBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/FabricCatalogue',
    staffBackendUrl:'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/staff',
    quickViewBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/pattern',
    eCommerceWebsiteUrl: 'http://highlanderdeluxe.com',
    promoCodeBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/PromoService',
    orderBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/OrderService',
    orderStatusLogBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/OrderStatusLogService',
    orderItemBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/OrderItemService',
    filterBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/GetFilters',
    filteredProductListBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ProductCatalogue/FilterBeddingPatterns',
    collectionBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/CollectionService',
    fabricBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/FabricService',
    colourBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/ColourService',
    patternBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/PatternService',
    beddingSizeBackendUrl: 'http://ec2-54-169-154-10.ap-southeast-1.compute.amazonaws.com/FYP-backend/API/BeddingSizeService'
}