-- MySQL Script generated by MySQL Workbench
-- 07/04/17 14:32:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff_role` (
  `role_code` VARCHAR(120) NOT NULL,
  `role_name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_num` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `role_code` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`email`, `role_code`),
  INDEX `fk_Stuff_Staff_role1_idx` (`role_code` ASC),
  CONSTRAINT `fk_Stuff_Staff_role1`
    FOREIGN KEY (`role_code`)
    REFERENCES `mydb`.`Staff_role` (`role_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_number` VARCHAR(120) NULL DEFAULT NULL,
  `address` VARCHAR(120) NULL DEFAULT NULL,
  `unit_number` VARCHAR(120) NULL DEFAULT NULL,
  `country` VARCHAR(120) NULL DEFAULT NULL,
  `postal_code` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `verified` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_time` TIME NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `payment_id` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pattern`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pattern` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pattern` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `thread_count_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_category` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
