-- MySQL Script generated by MySQL Workbench
-- 07/14/17 01:34:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COLLECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COLLECTION` (
  `COLLECTION_ID` VARCHAR(100) NOT NULL,
  `COLLECTION_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`COLLECTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `PATTERN_NAME` VARCHAR(100) NULL,
  `PATTERN_DESCRIPTION` VARCHAR(500) NULL,
  `PATTERN_PRICE` DOUBLE NULL,
  `COLLECTION_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PATTERN_ID`),
  INDEX `fk_PATTERN_COLLECTION_idx` (`COLLECTION_ID` ASC),
  CONSTRAINT `fk_PATTERN_COLLECTION`
    FOREIGN KEY (`COLLECTION_ID`)
    REFERENCES `mydb`.`COLLECTION` (`COLLECTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FABRIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FABRIC` (
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  `FABRIC_NAME` VARCHAR(100) NULL,
  `FABRIC_DESCRIPTION` VARCHAR(2000) NULL,
  `FABRIC_PRICE` DOUBLE NULL,
  PRIMARY KEY (`FABRIC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SIZE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SIZE` (
  `SIZE_NAME` VARCHAR(100) NOT NULL,
  `SIZE_PRICE` DOUBLE NULL,
  PRIMARY KEY (`SIZE_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLOUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COLOUR` (
  `COLOUR_ID` VARCHAR(100) NOT NULL,
  `COLOUR_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`COLOUR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN_FABRIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN_FABRIC` (
  `PF_ID` VARCHAR(100) NOT NULL,
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PF_ID`),
  INDEX `fk_PATTERN_has_FABRIC_FABRIC1_idx` (`FABRIC_ID` ASC),
  INDEX `fk_PATTERN_has_FABRIC_PATTERN1_idx` (`PATTERN_ID` ASC),
  CONSTRAINT `fk_PATTERN_has_FABRIC_PATTERN1`
    FOREIGN KEY (`PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN` (`PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_has_FABRIC_FABRIC1`
    FOREIGN KEY (`FABRIC_ID`)
    REFERENCES `mydb`.`FABRIC` (`FABRIC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLOUR_PRICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COLOUR_PRICE` (
  `PF_ID` VARCHAR(100) NOT NULL,
  `COLOUR_ID` VARCHAR(100) NOT NULL,
  `COLOUR_PRICE` DOUBLE NULL,
  PRIMARY KEY (`PF_ID`, `COLOUR_ID`),
  INDEX `fk_PATTERN_FABRIC_has_COLOUR_COLOUR1_idx` (`COLOUR_ID` ASC),
  INDEX `fk_PATTERN_FABRIC_has_COLOUR_PATTERN_FABRIC1_idx` (`PF_ID` ASC),
  CONSTRAINT `fk_PATTERN_FABRIC_has_COLOUR_PATTERN_FABRIC1`
    FOREIGN KEY (`PF_ID`)
    REFERENCES `mydb`.`PATTERN_FABRIC` (`PF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_FABRIC_has_COLOUR_COLOUR1`
    FOREIGN KEY (`COLOUR_ID`)
    REFERENCES `mydb`.`COLOUR` (`COLOUR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff_role` (
  `role_code` VARCHAR(120) NOT NULL,
  `role_name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_num` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `role_code` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`email`, `role_code`),
  INDEX `fk_Stuff_Staff_role1_idx` (`role_code` ASC),
  CONSTRAINT `fk_Stuff_Staff_role1`
    FOREIGN KEY (`role_code`)
    REFERENCES `mydb`.`Staff_role` (`role_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_number` VARCHAR(120) NULL DEFAULT NULL,
  `address` VARCHAR(120) NULL DEFAULT NULL,
  `country` VARCHAR(120) NULL DEFAULT NULL,
  `postal_code` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `verified` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_time` TIME NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `payment_id` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customer_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
