-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 00:35:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COLLECTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLLECTION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLLECTION` (
  `COLLECTION_ID` VARCHAR(100) NOT NULL,
  `COLLECTION_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`COLLECTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `PATTERN_NAME` VARCHAR(100) NULL,
  `PATTERN_DESCRIPTION` VARCHAR(500) NULL,
  `PATTERN_PRICE` DOUBLE NULL,
  `COLLECTION_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PATTERN_ID`),
  CONSTRAINT `fk_PATTERN_COLLECTION`
    FOREIGN KEY (`COLLECTION_ID`)
    REFERENCES `mydb`.`COLLECTION` (`COLLECTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_COLLECTION_idx` ON `mydb`.`PATTERN` (`COLLECTION_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FABRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FABRIC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FABRIC` (
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  `FABRIC_NAME` VARCHAR(100) NULL,
  `FABRIC_DESCRIPTION` VARCHAR(2000) NULL,
  `FABRIC_PRICE` DOUBLE NULL,
  PRIMARY KEY (`FABRIC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SIZE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SIZE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SIZE` (
  `SIZE_NAME` VARCHAR(100) NOT NULL,
  `SIZE_PRICE` DOUBLE NULL,
  PRIMARY KEY (`SIZE_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLOUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLOUR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLOUR` (
  `COLOUR_ID` VARCHAR(100) NOT NULL,
  `COLOUR_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`COLOUR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN_FABRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN_FABRIC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN_FABRIC` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`FABRIC_ID`, `PATTERN_ID`),
  CONSTRAINT `fk_PATTERN_has_FABRIC_PATTERN1`
    FOREIGN KEY (`PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN` (`PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_has_FABRIC_FABRIC1`
    FOREIGN KEY (`FABRIC_ID`)
    REFERENCES `mydb`.`FABRIC` (`FABRIC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_has_FABRIC_FABRIC1_idx` ON `mydb`.`PATTERN_FABRIC` (`FABRIC_ID` ASC);

CREATE INDEX `fk_PATTERN_has_FABRIC_PATTERN1_idx` ON `mydb`.`PATTERN_FABRIC` (`PATTERN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `SKU` VARCHAR(100) NOT NULL,
  `COLOUR_ID` VARCHAR(100) NOT NULL,
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `PRICE` DOUBLE NULL,
  `IMAGE_URL` VARCHAR(2000) NULL,
  PRIMARY KEY (`SKU`),
  CONSTRAINT `fk_PATTERN_FABRIC_has_COLOUR_COLOUR1`
    FOREIGN KEY (`COLOUR_ID`)
    REFERENCES `mydb`.`COLOUR` (`COLOUR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_LIST_PATTERN_FABRIC1`
    FOREIGN KEY (`FABRIC_ID` , `PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN_FABRIC` (`FABRIC_ID` , `PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_FABRIC_has_COLOUR_COLOUR1_idx` ON `mydb`.`PRODUCT` (`COLOUR_ID` ASC);

CREATE INDEX `fk_PRODUCT_LIST_PATTERN_FABRIC1_idx` ON `mydb`.`PRODUCT` (`FABRIC_ID` ASC, `PATTERN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAG` (
  `TAG_ID` VARCHAR(100) NOT NULL,
  `TAG_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`TAG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN_TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN_TAG` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `TAG_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PATTERN_ID`, `TAG_ID`),
  CONSTRAINT `fk_PATTERN_has_TAG_PATTERN1`
    FOREIGN KEY (`PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN` (`PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_has_TAG_TAG1`
    FOREIGN KEY (`TAG_ID`)
    REFERENCES `mydb`.`TAG` (`TAG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_has_TAG_TAG1_idx` ON `mydb`.`PATTERN_TAG` (`TAG_ID` ASC);

CREATE INDEX `fk_PATTERN_has_TAG_PATTERN1_idx` ON `mydb`.`PATTERN_TAG` (`PATTERN_ID` ASC);

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff_role` (
  `role_code` VARCHAR(120) NOT NULL,
  `role_name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_num` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `role_code` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`email`, `role_code`),
  CONSTRAINT `fk_Stuff_Staff_role1`
    FOREIGN KEY (`role_code`)
    REFERENCES `mydb`.`Staff_role` (`role_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Stuff_Staff_role1_idx` ON `mydb`.`Staff` (`role_code` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_number` VARCHAR(120) NULL DEFAULT NULL,
  `address` VARCHAR(120) NULL DEFAULT NULL,
  `country` VARCHAR(120) NULL DEFAULT NULL,
  `postal_code` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `verified` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_time` TIME NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `payment_id` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customer_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
