-- MySQL Script generated by MySQL Workbench
-- 07/04/17 11:01:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff_role` (
  `role_code` VARCHAR(120) NOT NULL,
  `role_name` VARCHAR(120) NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stuff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stuff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stuff` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL,
  `last_name` VARCHAR(120) NULL,
  `phone_num` VARCHAR(120) NULL,
  `password` VARCHAR(120) NULL,
  `role_code` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`email`, `role_code`),
  INDEX `fk_Stuff_Staff_role1_idx` (`role_code` ASC),
  CONSTRAINT `fk_Stuff_Staff_role1`
    FOREIGN KEY (`role_code`)
    REFERENCES `mydb`.`Staff_role` (`role_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL,
  `last_name` VARCHAR(120) NULL,
  `phone_num` VARCHAR(120) NULL,
  `address` VARCHAR(120) NULL,
  `postal_code` VARCHAR(120) NULL,
  `unit_number` VARCHAR(120) NULL,
  `verified` VARCHAR(1) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `order_date` DATE NULL,
  `order_time` TIME NULL,
  `price` DOUBLE NULL,
  `status` VARCHAR(45) NULL,
  `payment_id` VARCHAR(45) NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pattern`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pattern` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pattern` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `thread_count_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_category` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `Product_category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Product_category_id`),
  INDEX `fk_Product_Product_category1_idx` (`Product_category_id` ASC),
  CONSTRAINT `fk_Product_Product_category1`
    FOREIGN KEY (`Product_category_id`)
    REFERENCES `mydb`.`Product_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Size` (
  `id` INT NOT NULL,
  `size` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Size_Product1_idx` (`Product_id` ASC),
  CONSTRAINT `fk_Size_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `id` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Color_has_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Color_has_Product` (
  `Color_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`Color_id`, `Product_id`),
  INDEX `fk_Color_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Color_has_Product_Color1_idx` (`Color_id` ASC),
  CONSTRAINT `fk_Color_has_Product_Color1`
    FOREIGN KEY (`Color_id`)
    REFERENCES `mydb`.`Color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Color_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Pattern` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Material` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `id` INT NOT NULL,
  `material` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Material_Product1_idx` (`Product_id` ASC),
  CONSTRAINT `fk_Material_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pattern_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pattern_has_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pattern_has_Product` (
  `Pattern_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`Pattern_id`, `Product_id`),
  INDEX `fk_Pattern_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Pattern_has_Product_Pattern1_idx` (`Pattern_id` ASC),
  CONSTRAINT `fk_Pattern_has_Product_Pattern1`
    FOREIGN KEY (`Pattern_id`)
    REFERENCES `mydb`.`Pattern` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pattern_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_has_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Product` (
  `Order_id` INT NOT NULL,
  `Order_Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `Product_Product_category_id` INT NOT NULL,
  PRIMARY KEY (`Order_id`, `Order_Customer_id`, `Product_id`, `Product_Product_category_id`),
  INDEX `fk_Order_has_Product_Product1_idx` (`Product_id` ASC, `Product_Product_category_id` ASC),
  INDEX `fk_Order_has_Product_Order1_idx` (`Order_id` ASC, `Order_Customer_id` ASC),
  CONSTRAINT `fk_Order_has_Product_Order1`
    FOREIGN KEY (`Order_id` , `Order_Customer_id`)
    REFERENCES `mydb`.`Order` (`id` , `Customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Product1`
    FOREIGN KEY (`Product_id` , `Product_Product_category_id`)
    REFERENCES `mydb`.`Product` (`id` , `Product_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
