INSERT INTO COLLECTION VALUES ('CO1','Bestsellers');
INSERT INTO COLLECTION VALUES ('CO2','2018 Spring');
INSERT INTO COLLECTION VALUES ('CO3','2018 Summer');
INSERT INTO COLLECTION VALUES ('CO4','2017 Spring');
INSERT INTO COLLECTION VALUES ('CO5','2017 Winter');

INSERT INTO PATTERN VALUES ('P1','Retro','Hi, here is a description on retro',100,'CO1');
INSERT INTO PATTERN VALUES ('P2','Royal','Hi, here is a description on royal',120,'CO1');
INSERT INTO PATTERN VALUES ('P3','Flowers','Hi, here is a description on clouds',110,'CO2');
INSERT INTO PATTERN VALUES ('P4','Birds','Hi, here is a description of birds',100,'CO3');
INSERT INTO PATTERN VALUES ('P5','Clouds','Hi, here is a description on clouds',340,'CO4');
INSERT INTO PATTERN VALUES ('P6','Checkered','Hi, here is a description on checkered',700,'CO5');
INSERT INTO PATTERN VALUES ('P7','Stripes','Hi, here is a description on stripes',500,'CO5');
INSERT INTO PATTERN VALUES ('P8','Acid Wash','Hi, here is a description on acid wash',100,'CO1');
INSERT INTO PATTERN VALUES ('P9','Metallic','Hi, here is a description on metallic',300,'CO1');
INSERT INTO PATTERN VALUES ('P10','Hello Kitty','Hi, here is a description on hello kitty',1000,'CO2');
INSERT INTO PATTERN VALUES ('P11','Pokemon','Hi, here is a description on pokemon',400,'CO3');
INSERT INTO PATTERN VALUES ('P12','Spiderman','Hi, here is a description on spiderman',200,'CO3');

INSERT INTO FABRIC VALUES('F1','Silk','Silk, also known as natural silk, is continuous filament solidified from the silk fluid secreted by silkworms during cocooning. It is a natural protein fiber and also one of the earliest fibers to be woven into textiles. Second to none in texture, shine, strength and drape, silk is renowned as “the second skin of human body” and “The Queen of Fibers” in the industry.',250);
INSERT INTO FABRIC VALUES('F2','Modal','Modal fabric is a regenerated cellulose fiber developed by the Lenzing company from Austria. Its raw materials are beech trees living in European bushes. Beech trees are made into wood pulp first and then processed into Modal fiber using special spinning technologies. The textile made from this fiber has a silky shine, fine touch, and excellent draping. Modal fiber is an eco-friendly fiber because all its raw materials are natural and can be naturally decomposed.',100);
INSERT INTO FABRIC VALUES('F3','Long Staple Cotton','Long staple cotton, also called sea island cotton, is a cultivated cotton species that is known for its long fiber. Long staple cotton is renowned as fine cotton for its high quality and long soft fiber.',120);
INSERT INTO FABRIC VALUES('F4','Cotton','Cotton is a widely used home textile fabric. Popular among consumers because of its features such as perspiration absorbent, breezy for wear, softness and no irritation to skin, ease of wash, and no pilling.',80);
INSERT INTO FABRIC VALUES('F5','Lyocell Tencel','Lyocell, also called Tencel, is a form of rayon which consists of cellulose fiber made from dissolving pulp (bleached wood pulp) using dry jet-wet spinning. It is a typical eco-friendly fiber developed by the Austria Lenzing company. The decomposition rate of Tencel in mud is over 99%, causing little pollution. Tencel is hygroscopic, comfortable, and draping. Tencel products are more hygroscopic than cotton products, softer than silk products, and cooler than linen products. That is why Tencel is called “green fiber of the 21st century”.',450);
INSERT INTO FABRIC VALUES('F6','Polyester-Cotton','Polyester-cotton called by a joint name of polyester blend cotton combination fabric,and it is the textile which made by the yarn of 65%—67% polyester blended with 33%—35% cotton.',200);

INSERT INTO PATTERN_FABRIC VALUES('P1F1','P1','F1');
INSERT INTO PATTERN_FABRIC VALUES('P2F1','P2','F1');
INSERT INTO PATTERN_FABRIC VALUES('P2F2','P2','F2');
INSERT INTO PATTERN_FABRIC VALUES('P2F3','P2','F3');
INSERT INTO PATTERN_FABRIC VALUES('P3F4','P3','F4');
INSERT INTO PATTERN_FABRIC VALUES('P3F5','P3','F5');
INSERT INTO PATTERN_FABRIC VALUES('P4F1','P4','F1');
INSERT INTO PATTERN_FABRIC VALUES('P4F6','P4','F6');
INSERT INTO PATTERN_FABRIC VALUES('P5F1','P5','F1');
INSERT INTO PATTERN_FABRIC VALUES('P5F2','P5','F2');
INSERT INTO PATTERN_FABRIC VALUES('P5F3','P5','F3');
INSERT INTO PATTERN_FABRIC VALUES('P6F6','P6','F6');
INSERT INTO PATTERN_FABRIC VALUES('P7F1','P7','F1');
INSERT INTO PATTERN_FABRIC VALUES('P8F6','P8','F6');
INSERT INTO PATTERN_FABRIC VALUES('P9F6','P9','F6');
INSERT INTO PATTERN_FABRIC VALUES('P10F6','P10','F6');
INSERT INTO PATTERN_FABRIC VALUES('P11F6','P11','F6');
INSERT INTO PATTERN_FABRIC VALUES('P12F1','P12','F1');
INSERT INTO PATTERN_FABRIC VALUES('P12F6','P12','F6');

INSERT INTO SIZE VALUES('Single',100);
INSERT INTO SIZE VALUES('Double',200);
INSERT INTO SIZE VALUES('Queen',300);
INSERT INTO SIZE VALUES('King',400);

INSERT INTO COLOUR VALUES('C1','White');
INSERT INTO COLOUR VALUES('C2','Black');
INSERT INTO COLOUR VALUES('C3','Red');
INSERT INTO COLOUR VALUES('C4','Yellow');
INSERT INTO COLOUR VALUES('C5','Blue');
INSERT INTO COLOUR VALUES('C6','Green');
INSERT INTO COLOUR VALUES('C7','Pink');
INSERT INTO COLOUR VALUES('C8','Purple');
INSERT INTO COLOUR VALUES('C9','Brown');
INSERT INTO COLOUR VALUES('C10','Gold');
INSERT INTO COLOUR VALUES('C11','Silver');

INSERT INTO COLOUR_PRICE VALUES('P1F1','C1',100);
INSERT INTO COLOUR_PRICE VALUES('P1F1','C2',100);
INSERT INTO COLOUR_PRICE VALUES('P1F1','C3',120);
INSERT INTO COLOUR_PRICE VALUES('P1F1','C4',200);
INSERT INTO COLOUR_PRICE VALUES('P2F1','C6',900);
INSERT INTO COLOUR_PRICE VALUES('P2F2','C1',500);
INSERT INTO COLOUR_PRICE VALUES('P2F2','C2',300);
INSERT INTO COLOUR_PRICE VALUES('P2F3','C1',200);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C2',100);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C6',300);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C7',300);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C8',200);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C9',400);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C10',500);
INSERT INTO COLOUR_PRICE VALUES('P3F4','C11',300);
INSERT INTO COLOUR_PRICE VALUES('P3F5','C2',120);
INSERT INTO COLOUR_PRICE VALUES('P4F1','C10',900);
INSERT INTO COLOUR_PRICE VALUES('P4F6','C11',200);
INSERT INTO COLOUR_PRICE VALUES('P5F1','C5',300);
INSERT INTO COLOUR_PRICE VALUES('P5F1','C4',200);
INSERT INTO COLOUR_PRICE VALUES('P5F2','C10',100);
INSERT INTO COLOUR_PRICE VALUES('P5F3','C9',200);
INSERT INTO COLOUR_PRICE VALUES('P6F6','C6',600);
INSERT INTO COLOUR_PRICE VALUES('P7F1','C6',200);
INSERT INTO COLOUR_PRICE VALUES('P8F6','C6',200);
INSERT INTO COLOUR_PRICE VALUES('P9F6','C6',100);
INSERT INTO COLOUR_PRICE VALUES('P10F6','C6',200);
INSERT INTO COLOUR_PRICE VALUES('P11F6','C6',400);
INSERT INTO COLOUR_PRICE VALUES('P12F1','C6',500);
INSERT INTO COLOUR_PRICE VALUES('P12F6','C1',500);
