-- MySQL Script generated by MySQL Workbench
-- 08/24/17 15:43:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COLLECTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLLECTION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLLECTION` (
  `COLLECTION_ID` INT NOT NULL,
  `COLLECTION_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COLLECTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `PATTERN_NAME` VARCHAR(100) NULL,
  `PATTERN_DESCRIPTION` VARCHAR(500) NULL,
  `PATTERN_PRICE` DOUBLE NULL,
  `COLLECTION_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PATTERN_ID`),
  CONSTRAINT `fk_PATTERN_COLLECTION`
    FOREIGN KEY (`COLLECTION_ID`)
    REFERENCES `mydb`.`COLLECTION` (`COLLECTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_COLLECTION_idx` ON `mydb`.`PATTERN` (`COLLECTION_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FABRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FABRIC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FABRIC` (
  `FABRIC_ID` INT NOT NULL,
  `FABRIC_NAME` VARCHAR(45) NOT NULL,
  `FABRIC_DESC` VARCHAR(500) NOT NULL,
  `FABRIC_PRICE` DOUBLE NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`FABRIC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SIZE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SIZE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SIZE` (
  `SIZE_NAME` VARCHAR(100) NOT NULL,
  `SIZE_PRICE` DOUBLE NULL,
  PRIMARY KEY (`SIZE_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLOUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLOUR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLOUR` (
  `COLOUR_ID` INT NOT NULL,
  `COLOUR_NAME` VARCHAR(45) NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`COLOUR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN_FABRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN_FABRIC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN_FABRIC` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `FABRIC_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`FABRIC_ID`, `PATTERN_ID`),
  CONSTRAINT `fk_PATTERN_has_FABRIC_PATTERN1`
    FOREIGN KEY (`PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN` (`PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_has_FABRIC_FABRIC1`
    FOREIGN KEY (`FABRIC_ID`)
    REFERENCES `mydb`.`FABRIC` (`FABRIC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_has_FABRIC_FABRIC1_idx` ON `mydb`.`PATTERN_FABRIC` (`FABRIC_ID` ASC);

CREATE INDEX `fk_PATTERN_has_FABRIC_PATTERN1_idx` ON `mydb`.`PATTERN_FABRIC` (`PATTERN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_TYPE` VARCHAR(45) NULL,
  `DESIGN_ID` VARCHAR(45) NULL,
  `COLOUR_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_FABRIC_has_COLOUR_COLOUR1_idx` ON `mydb`.`PRODUCT` (`COLOUR_ID` ASC);

CREATE INDEX `fk_PRODUCT_LIST_PATTERN_FABRIC1_idx` ON `mydb`.`PRODUCT` (`FABRIC_ID` ASC, `PATTERN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAG` (
  `TAG_ID` INT NOT NULL,
  `TAG_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TAG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATTERN_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATTERN_TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATTERN_TAG` (
  `PATTERN_ID` VARCHAR(100) NOT NULL,
  `TAG_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PATTERN_ID`, `TAG_ID`),
  CONSTRAINT `fk_PATTERN_has_TAG_PATTERN1`
    FOREIGN KEY (`PATTERN_ID`)
    REFERENCES `mydb`.`PATTERN` (`PATTERN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATTERN_has_TAG_TAG1`
    FOREIGN KEY (`TAG_ID`)
    REFERENCES `mydb`.`TAG` (`TAG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PATTERN_has_TAG_TAG1_idx` ON `mydb`.`PATTERN_TAG` (`TAG_ID` ASC);

CREATE INDEX `fk_PATTERN_has_TAG_PATTERN1_idx` ON `mydb`.`PATTERN_TAG` (`PATTERN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_number` VARCHAR(120) NULL DEFAULT NULL,
  `address` VARCHAR(120) NULL DEFAULT NULL,
  `country` VARCHAR(120) NULL DEFAULT NULL,
  `postal_code` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `verified` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` INT NOT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_time` TIME NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `payment_id` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`order_id`, `Customer_email`),
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_email`)
    REFERENCES `mydb`.`Customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Order_Customer1_idx` ON `mydb`.`Order` (`Customer_email` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Order_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_Details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_Details` (
  `order_id` INT NOT NULL,
  `PRODUCT_SKU` VARCHAR(100) NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`order_id`, `PRODUCT_SKU`),
  CONSTRAINT `fk_Order_Details_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Details_PRODUCT1`
    FOREIGN KEY (`PRODUCT_SKU`)
    REFERENCES `mydb`.`PRODUCT` (`SKU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Order_Details_Order1_idx` ON `mydb`.`Order_Details` (`order_id` ASC);

CREATE INDEX `fk_Order_Details_PRODUCT1_idx` ON `mydb`.`Order_Details` (`PRODUCT_SKU` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cart` (
  `cart_id` VARCHAR(100) NOT NULL,
  `price` VARCHAR(100) NULL DEFAULT NULL,
  `customer_id` VARCHAR(100) NULL,
  `date` VARCHAR(100) NULL,
  PRIMARY KEY (`cart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cart_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cart_Details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cart_Details` (
  `cart_id` VARCHAR(100) NOT NULL,
  `PRODUCT_SKU` VARCHAR(100) NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`cart_id`, `PRODUCT_SKU`),
  CONSTRAINT `fk_Cart_Details_Cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `mydb`.`Cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_Details_PRODUCT1`
    FOREIGN KEY (`PRODUCT_SKU`)
    REFERENCES `mydb`.`PRODUCT` (`SKU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cart_Details_PRODUCT1_idx` ON `mydb`.`Cart_Details` (`PRODUCT_SKU` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FABRIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FABRIC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FABRIC` (
  `FABRIC_ID` INT NOT NULL,
  `FABRIC_NAME` VARCHAR(45) NOT NULL,
  `FABRIC_DESC` VARCHAR(500) NOT NULL,
  `FABRIC_PRICE` DOUBLE NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`FABRIC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BEDDING_SIZE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BEDDING_SIZE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BEDDING_SIZE` (
  `SIZE_NAME` VARCHAR(45) NOT NULL,
  `DIMENSIONS` VARCHAR(500) NOT NULL,
  `SIZE_PRICE` DOUBLE NOT NULL,
  PRIMARY KEY (`SIZE_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BEDDING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BEDDING` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BEDDING` (
  `PRODUCT_ID` INT NOT NULL,
  `COLOUR_PRICE` DOUBLE NOT NULL,
  `FABRIC_ID` INT NOT NULL,
  `SIZE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  CONSTRAINT `fk_BEDDING_FABRIC1`
    FOREIGN KEY (`FABRIC_ID`)
    REFERENCES `mydb`.`FABRIC` (`FABRIC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BEDDING_BEDDING_SIZE1`
    FOREIGN KEY (`SIZE_NAME`)
    REFERENCES `mydb`.`BEDDING_SIZE` (`SIZE_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_BEDDING_FABRIC1_idx` ON `mydb`.`BEDDING` (`FABRIC_ID` ASC);

CREATE INDEX `fk_BEDDING_BEDDING_SIZE1_idx` ON `mydb`.`BEDDING` (`SIZE_NAME` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`COLLECTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLLECTION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLLECTION` (
  `COLLECTION_ID` INT NOT NULL,
  `COLLECTION_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COLLECTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DESIGN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DESIGN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DESIGN` (
  `DESIGN_ID` INT NOT NULL,
  `DESIGN_NAME` VARCHAR(45) NOT NULL,
  `DESIGN_DESC` VARCHAR(500) NOT NULL,
  `DESIGN_PRICE` DOUBLE NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  `COLLECTION_ID` INT NOT NULL,
  PRIMARY KEY (`DESIGN_ID`),
  CONSTRAINT `fk_DESIGN_COLLECTION1`
    FOREIGN KEY (`COLLECTION_ID`)
    REFERENCES `mydb`.`COLLECTION` (`COLLECTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DESIGN_COLLECTION1_idx` ON `mydb`.`DESIGN` (`COLLECTION_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`COLOUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLOUR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COLOUR` (
  `COLOUR_ID` INT NOT NULL,
  `COLOUR_NAME` VARCHAR(45) NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`COLOUR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_TYPE` VARCHAR(45) NULL,
  `DESIGN_ID` VARCHAR(45) NULL,
  `COLOUR_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCT_BEDDING1_idx` ON `mydb`.`PRODUCT` (`PRODUCT_ID` ASC);

CREATE INDEX `fk_PRODUCT_DESIGN1_idx` ON `mydb`.`PRODUCT` (`DESIGN_ID` ASC);

CREATE INDEX `fk_PRODUCT_COLOUR1_idx` ON `mydb`.`PRODUCT` (`COLOUR_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_TYPE` VARCHAR(45) NULL,
  `DESIGN_ID` VARCHAR(45) NULL,
  `COLOUR_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT_IMAGE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_IMAGE` (
  `PRODUCT_ID` INT NOT NULL,
  `IMAGE_ID` INT NOT NULL,
  `IMAGE_URL` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`, `IMAGE_ID`),
  CONSTRAINT `fk_table1_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAG` (
  `TAG_ID` INT NOT NULL,
  `TAG_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TAG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROMO_CODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROMO_CODE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROMO_CODE` (
  `PROMO_CODE_ID` INT NOT NULL,
  `PROMO_NAME` VARCHAR(100) NOT NULL,
  `PROMO_TYPE` VARCHAR(45) NOT NULL,
  `PROMO_VALUE` DOUBLE NOT NULL,
  `MIN_PURCHASE` DOUBLE NOT NULL,
  `MAX_DISCOUNT` DOUBLE NOT NULL,
  `QUOTA` INT NOT NULL,
  `COUNTER` INT NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NOT NULL,
  `DELETED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`PROMO_CODE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CUSTOMER` (
  `EMAIL` VARCHAR(200) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `PHONE_NO` VARCHAR(8) NOT NULL,
  `PASSWORD` VARCHAR(120) NOT NULL,
  `VERIFIED` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUSTOMER_ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CUSTOMER_ADDRESS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CUSTOMER_ADDRESS` (
  `ADDRESS_ID` INT NOT NULL,
  `EMAIL` VARCHAR(200) NOT NULL,
  `ADDRESS_LINE` VARCHAR(200) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `POSTAL_CODE` VARCHAR(6) NOT NULL,
  `ISDEFAULT` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ADDRESS_ID`, `EMAIL`),
  CONSTRAINT `fk_CUSTOMER_ADDRESS_CUSTOMER1`
    FOREIGN KEY (`EMAIL`)
    REFERENCES `mydb`.`CUSTOMER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAFF_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STAFF_ROLE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STAFF_ROLE` (
  `ROLE_ID` INT NOT NULL,
  `ROLE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ROLE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STAFF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STAFF` (
  `EMAIL` VARCHAR(200) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `PHONE_NO` VARCHAR(8) NOT NULL,
  `PASSWORD` VARCHAR(120) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`EMAIL`),
  CONSTRAINT `fk_STAFF_STAFF_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `mydb`.`STAFF_ROLE` (`ROLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_STAFF_STAFF_ROLE1_idx` ON `mydb`.`STAFF` (`ROLE_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDER` (
  `ORDER_ID` INT NOT NULL,
  `ORDER_DATE` TIMESTAMP(8) NOT NULL,
  `NET_AMT` DOUBLE NOT NULL,
  `PROMO_DISC_AMT` DOUBLE NOT NULL,
  `ADDRESS_LINE` VARCHAR(200) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `POSTAL_CODE` VARCHAR(6) NOT NULL,
  `PAYMENT_REF_NO` VARCHAR(120) NOT NULL,
  `EMAIL` VARCHAR(200) NOT NULL,
  `PROMO_CODE_ID` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  CONSTRAINT `fk_ORDER_PROMO_CODE1`
    FOREIGN KEY (`PROMO_CODE_ID`)
    REFERENCES `mydb`.`PROMO_CODE` (`PROMO_CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_CUSTOMER1`
    FOREIGN KEY (`EMAIL`)
    REFERENCES `mydb`.`CUSTOMER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ORDER_PROMO_CODE1_idx` ON `mydb`.`ORDER` (`PROMO_CODE_ID` ASC);

CREATE INDEX `fk_ORDER_CUSTOMER1_idx` ON `mydb`.`ORDER` (`EMAIL` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDER_ITEM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDER_ITEM` (
  `ORDER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `QUANTITY` INT NOT NULL,
  `UNIT_PRICE` DOUBLE NOT NULL,
  PRIMARY KEY (`ORDER_ID`, `PRODUCT_ID`),
  CONSTRAINT `fk_ORDER_DETAILS_ORDER1`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mydb`.`ORDER` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_DETAILS_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ORDER_DETAILS_PRODUCT1_idx` ON `mydb`.`ORDER_ITEM` (`PRODUCT_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDER_STATUS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDER_STATUS` (
  `STATUS_ID` INT NOT NULL,
  `STATUS_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`STATUS_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_STATUS_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDER_STATUS_LOG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDER_STATUS_LOG` (
  `ORDER_ID` INT NOT NULL,
  `STATUS_ID` INT NOT NULL,
  `TIMESTAMP` TIMESTAMP(10) NOT NULL,
  PRIMARY KEY (`ORDER_ID`, `STATUS_ID`),
  CONSTRAINT `fk_ORDER_STATUS_LOG_ORDER_STATUS1`
    FOREIGN KEY (`STATUS_ID`)
    REFERENCES `mydb`.`ORDER_STATUS` (`STATUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_STATUS_LOG_ORDER1`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mydb`.`ORDER` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ORDER_STATUS_LOG_ORDER_STATUS1_idx` ON `mydb`.`ORDER_STATUS_LOG` (`STATUS_ID` ASC);

CREATE INDEX `fk_ORDER_STATUS_LOG_ORDER1_idx` ON `mydb`.`ORDER_STATUS_LOG` (`ORDER_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`DESIGN_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DESIGN_TAG` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DESIGN_TAG` (
  `DESIGN_ID` INT NOT NULL,
  `TAG_ID` INT NOT NULL,
  PRIMARY KEY (`DESIGN_ID`, `TAG_ID`),
  CONSTRAINT `fk_DESIGN_has_TAG_DESIGN1`
    FOREIGN KEY (`DESIGN_ID`)
    REFERENCES `mydb`.`DESIGN` (`DESIGN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESIGN_has_TAG_TAG1`
    FOREIGN KEY (`TAG_ID`)
    REFERENCES `mydb`.`TAG` (`TAG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DESIGN_has_TAG_TAG1_idx` ON `mydb`.`DESIGN_TAG` (`TAG_ID` ASC);

CREATE INDEX `fk_DESIGN_has_TAG_DESIGN1_idx` ON `mydb`.`DESIGN_TAG` (`DESIGN_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`LAMP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LAMP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LAMP` (
  `PRODUCT_ID` INT NOT NULL,
  `LAMP_TYPE` VARCHAR(45) NOT NULL,
  `LAMP_PRICE` DOUBLE NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  CONSTRAINT `fk_LAMP_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_LAMP_PRODUCT1_idx` ON `mydb`.`LAMP` (`PRODUCT_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CART` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CART` (
  `CART_ID` INT NOT NULL,
  `CART_PRICE` DOUBLE NOT NULL,
  `EMAIL` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CART_ID`),
  CONSTRAINT `fk_SHOPPING_CART_CUSTOMER1`
    FOREIGN KEY (`EMAIL`)
    REFERENCES `mydb`.`CUSTOMER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SHOPPING_CART_CUSTOMER1_idx` ON `mydb`.`CART` (`EMAIL` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`CART_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CART_ITEM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CART_ITEM` (
  `CART_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `QUANTITY` INT NOT NULL,
  PRIMARY KEY (`CART_ID`, `PRODUCT_ID`),
  CONSTRAINT `fk_CART_DETAILS_SHOPPING_CART1`
    FOREIGN KEY (`CART_ID`)
    REFERENCES `mydb`.`CART` (`CART_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CART_DETAILS_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CART_DETAILS_PRODUCT1_idx` ON `mydb`.`CART_ITEM` (`PRODUCT_ID` ASC);

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff_role` (
  `role_code` VARCHAR(120) NOT NULL,
  `role_name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`role_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `email` VARCHAR(120) NOT NULL,
  `first_name` VARCHAR(120) NULL DEFAULT NULL,
  `last_name` VARCHAR(120) NULL DEFAULT NULL,
  `phone_num` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `role_code` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`email`, `role_code`),
  CONSTRAINT `fk_Stuff_Staff_role1`
    FOREIGN KEY (`role_code`)
    REFERENCES `mydb`.`Staff_role` (`role_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Stuff_Staff_role1_idx` ON `mydb`.`Staff` (`role_code` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
